SELECT a.employee_id, 
		a.FIRST_name, 
		a.last_name
FROM EMPLOYEES a;

SELECT e.PHONE_NUMBER , 
		e.HIRE_DATE , 
		e.SALARY 
FROM EMPLOYEES e;

SELECT e.first_name "이름",
		e.last_name "성",
		e.salary "급여",
		e.phone_number AS phoneNum,
		e.email "이메일"
FROM EMPLOYEES e;
--문장은 싱글쿼트를 사용한다
SELECT FIRST_name || ' ' || last_name "이름"
FROM EMPLOYEES;

SELECT first_name, salary, salary*12, (salary+300)*12
FROM EMPLOYEES;

SELECT first_name || '-' || last_name "성명",
		salary "급여",
		salary*12 "연봉",
		salary*12+5000 "연봉2",
		phone_number
FROM EMPLOYEES;

SELECT e.FIRST_NAME FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 10;

SELECT e.FIRST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE SALARY >= 15000;

SELECT e.FIRST_NAME 
FROM EMPLOYEES e 
WHERE SALARY <= 14000
OR SALARY >= 17000;

SELECT e.FIRST_NAME 
FROM EMPLOYEES e 
WHERE HIRE_DATE  >= '04/01/01'
and HIRE_DATE  <= '05/12/31';

SELECT FIRST_NAME 
FROM EMPLOYEES e 
WHERE FIRST_NAME IN ('Neena', 'Lex', 'John');

SELECT e.FIRST_NAME , e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE FIRST_Name LIKE 'L%'; --%는 길이를 모를 때, _는 글자수를 정확하게 알 때 

SELECT e.FIRST_NAME, e.SALARY, COMMISSION_PCT  
FROM EMPLOYEES e 
WHERE COMMISSION_PCT IS not NULL;

SELECT e.FIRST_NAME, e.SALARY, e.LAST_NAME, e.DEPARTMENT_ID  
FROM EMPLOYEES e 
ORDER BY DEPARTMENT_ID asc, 2 desc;

SELECT e.DEPARTMENT_ID "부서번호" , e.SALARY "급여" , e.LAST_NAME || ' '|| e.FIRST_NAME  "이름"
FROM EMPLOYEES e 
ORDER BY DEPARTMENT_ID

SELECT e.LAST_NAME || ' '|| e.FIRST_NAME  "이름", e.SALARY "급여" 
FROM EMPLOYEES e 
WHERE SALARY >= 5000
ORDER BY SALARY DESC;

SELECT e.DEPARTMENT_ID , e.SALARY , e.FIRST_NAME 
FROM EMPLOYEES e 
ORDER BY DEPARTMENT_ID, SALARY DESC ; 

SELECT e.EMAIL,INITCAP(e.EMAIL), e.DEPARTMENT_ID  
FROM EMPLOYEES e; --;은 생략 가능 

SELECT e.FIRST_NAME , SUBSTR(FIRST_NAME, 1, 3), SUBSTR(FIRST_NAME, -3, 2) 
FROM EMPLOYEES e ;

SELECT FIRST_NAME ,
		lpad(FIRST_NAME, 20, '*'),
		rpad(FIRST_NAME, 20, '*')
FROM EMPLOYEES; 

SELECT  FIRST_NAME , REPLACE (FIRST_NAME, 'a', '*')
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 100 ;

SELECT SYSDATE  FROM dual;

SELECT FIRST_NAME , HIRE_DATE , MONTHS_BETWEEN(SYSDATE, HIRE_DATE) "근속 개월수"
FROM EMPLOYEES e
WHERE DEPARTMENT_ID  = 100
ORDER BY 3 DESC ;

SELECT MONTHS_BETWEEN(SYSDATE, '2022-01-01') FROM dual;

SELECT FIRST_name, TO_CHAR(SALARY*12, '$999,999.99') "SAL"
FROM EMPLOYEES
WHERE DEPARTMENT_ID  = 110;

SELECT SYSDATE, TO_CHAR(sysdate, 'yyyy-mm-dd hh24:MI:SS')
FROM dual;

SELECT commission_pct, nvl(COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT COMMISSION_PCT , nvl2(COMMISSION_PCT, 100, 0)
FROM EMPLOYEES ;

--예제 1
SELECT FIRST_NAME || ' ' || LAST_NAME  AS 이름, SALARY AS 월급, PHONE_NUMBER AS 전화번호, HIRE_DATE AS 입사일 
FROM EMPLOYEES
ORDER BY HIRE_DATE ;

--예제 2
SELECT JOB_ID , SALARY 
FROM EMPLOYEES
ORDER BY SALARY DESC;

--예제 3
SELECT FIRST_NAME , MANAGER_ID , COMMISSION_PCT , SALARY 
FROM EMPLOYEES 
WHERE (MANAGER_ID IS NOT NULL
AND COMMISSION_PCT IS NULL)
AND SALARY > 3000

--예제 4
SELECT JOB_TITLE, MAX_SALARY 
FROM JOBS
WHERE max_salary > 10000
ORDER BY MAX_SALARY DESC;

--예제 5
SELECT FIRST_NAME , SALARY , nvl(COMMISSION_PCT, 0) 
FROM EMPLOYEES 
WHERE SALARY < 14000 AND SALARY >= 10000
ORDER BY SALARY  DESC ;

--예제 6

SELECT FIRST_NAME, SALARY , TO_CHAR(HIRE_DATE, 'yyyy-mm')  , DEPARTMENT_ID 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID in(10, 90, 100);

--예제 7
SELECT FIRST_NAME , SALARY 
FROM EMPLOYEES 
WHERE upper(FIRST_NAME) LIKE '%S%';

--예제 8
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS 
ORDER BY LENGTH(DEPARTMENT_NAME) DESC;

--예제 9, distinct: 자료를 조사할 때 중복을 제거하고 보여주는 메소드
--SELECT upper(COUNTRY_NAME) 
--FROM COUNTRIES 
--WHERE REGION_ID IS NOT NULL

SELECT UPPER(c.COUNTRY_NAME)  FROM COUNTRIES c 
WHERE c.COUNTRY_ID IN ('US', 'CA', 'DE', 'UK')
ORDER BY 1;

-- 모범답안
-- 정확하지 않지만, 지사가 있을 것으로 예상되는 나라들을 나라이름을 
-- 대문자로 출력하고 오름차순(ASC)으로 정렬해 보세오.

SELECT DISTINCT d.LOCATION_ID 
FROM DEPARTMENTS d ;

SELECT DISTINCT l.COUNTRY_ID 
FROM LOCATIONS l 
WHERE l.LOCATION_ID IN (1800,
2400,
1400,
2500,
1700,
2700,
1500);

SELECT UPPER(c.COUNTRY_NAME)  
FROM COUNTRIES c 
WHERE c.COUNTRY_ID IN ('US',
'CA',
'DE',
'UK')
ORDER BY 1;


--예제 10
SELECT FIRST_NAME , SALARY , REPLACE (PHONE_NUMBER, '.', '-') , HIRE_DATE 
FROM EMPLOYEES 
WHERE HIRE_DATE <= '2003-12-31';
