SELECT CONCAT('A', 'B') FROM dual;

SELECT *
FROM EMPLOYEES e 
WHERE department_id = 50;

CREATE OR REPLACE VIEW emp_v1 AS
SELECT *
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 50;

SELECT *
FROM emp_v1;

SELECT *FROM emp_v1
WHERE salary > 2500;

CREATE OR REPLACE VIEW emp_v2 AS
SELECT e.EMPLOYEE_ID , e.FIRST_NAME , e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 10
UNION
SELECT e.EMPLOYEE_ID, e.FIRST_NAME , e.LAST_NAME , e.SALARY
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 20;

SELECT *
FROM emp_v2;

SELECT * FROM EMPLOYEES e WHERE e.EMPLOYEE_ID in(10, 20);

SELECT /*+ use merge(e, d)*/ 
	e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME  
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID; 

SELECT
	e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID



SELECT 
   (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_LANGUAGE')
    || '_' ||
    (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_TERRITORY')
    || '.' ||
    (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_CHARACTERSET')
FROM DUAL


CALL CLIENT_CREATE('김태훈', '19930101', '010-1111-1111', '서울시 종로구', 'taehoon@gmail.com');

CALL CLIENT_CREATE(5003, '조영진', '19960202', '010-2222-2222', '서울시 성북구', 'youngjin@gmail.com');

CALL CLIENT_CREATE(5002, '김태훈', '19930101', '010-1111-1111', '서울시 종로구', 'taehoon@gmail.com');

CALL CLIENT_CREATE(5004, '박병규', '19900303', '010-3333-3333', '서울시 마포구', 'bbq@gmail.com');

CALL CLIENT_CREATE(5001, '박진석', '19960511', '010-5270-9694', '서울시 종로구', 'errandt@gmail.com');

CALL PRODUCT_CREATE(1002, 'T2', 15000000, 'CT');

CALL PRODUCT_UPDATE(1002, 'T2', 15000000, 'CT');
SELECT count(*)
FROM CLIENTDB; 